### ISSUE TITLE
Replace globals with local variables

### ISSUE THREAD

**Issue by aaditkamat** [sushinoya/leetcode-downloader#7]
The globals `LOGIN_URL`,  `PROBLEMS_URL` and `DIRECTORY` are used only in one function each hence they should be used as local variables in the respective functions. The global `SUBMISSIONS_URL` should be removed because it is not referenced anywhere. Only global object remaining should be the `CLIENT` object because it is used in several places.

**Comment by sushinoya** [comment]
They are not local variables because they are constants. I believe it is a good practice to have a separate constants file or instantiate them on the top instead of having them as magic strings in the code. Let's say if one day Leetcode decides to change its api url, you shouldn't have to go into the code to find where it was used and change it there. [Here](https://help.semmle.com/wiki/display/JAVA/Magic+strings%3A+use+defined+constant) is some context on magic stings.
